const PRODUCTS = [
  {
    id: 1,
    title: "Once Upon A Time In Hollywood",
    author: "Quentin Tarantino",
    gender: "Ficcion",
    price: 2024,
  },
  {
    id: 2,
    title: "A Clockwork Orange",
    author: "Anthony Burguess",
    gender: "Ultraviolence",
    price: 4684,
  },
  {
    id: 3,
    title: "Lolita",
    author: "Vladimir Nabokov",
    gender: "Ficcion",
    price: 2024,
  },
  {
    id: 4,
    title: "The Tell-Tale Heart",
    author: "Edgar Allan Poe",
    gender: "Horror",
    price: 8566,
  },
  {
    id: 5,
    title: "The Raven",
    author: "Edgar Allan Poe",
    gender: "Horror",
    price: 8655,
  },
  {
    id: 6,
    title: "The Murders In The Rue Morgue",
    author: "Edgar Allan Poe",
    gender: "Horror",
    price: 2378,
  },
  {
    id: 7,
    title: "The Black Cat",
    author: "Edgar Allan Poe",
    gender: "Horror",
    price: 5767,
  },
  {
    id: 8,
    title: "The Fall Of The House Of Usher",
    author: "Edgar Allan Poe",
    gender: "Horror",
    price: 1355,
  },
  {
    id: 9,
    title: "The Cask Of Amontillado",
    author: "Edgar Allan Poe",
    gender: "Horror",
    price: 7456,
  },
  {
    id: 10,
    title: "Berenice",
    author: "Edgar Allan Poe",
    gender: "Horror",
    price: 2355,
  },
];
